version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/myapp
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
